/* ***
 * Lists for autocomplete input fields.
 */

const countries = [
  'Afghanistan',
  'Albania',
  'Algeria',
  'Andorra',
  'Angola',
  'Antigua & Deps',
  'Argentina',
  'Armenia',
  'Australia',
  'Austria',
  'Azerbaijan',
  'Bahamas',
  'Bahrain',
  'Bangladesh',
  'Barbados',
  'Belarus',
  'Belgium',
  'Belize',
  'Benin',
  'Bhutan',
  'Bolivia',
  'Bosnia Herzegovina',
  'Botswana',
  'Brazil',
  'Brunei',
  'Bulgaria',
  'Burkina',
  'Burundi',
  'Cambodia',
  'Cameroon',
  'Canada',
  'Cape Verde',
  'Central African Rep',
  'Chad',
  'Chile',
  'China',
  'Colombia',
  'Comoros',
  'Congo',
  'Congo',
  'Costa Rica',
  'Croatia',
  'Cuba',
  'Cyprus',
  'Czech Republic',
  'Denmark',
  'Djibouti',
  'Dominica',
  'Dominican Republic',
  'East Timor',
  'Ecuador',
  'Egypt',
  'El Salvador',
  'Equatorial Guinea',
  'Eritrea',
  'Estonia',
  'Ethiopia',
  'Fiji',
  'Finland',
  'France',
  'Gabon',
  'Gambia',
  'Georgia',
  'Germany',
  'Ghana',
  'Greece',
  'Grenada',
  'Guatemala',
  'Guinea',
  'Guinea-Bissau',
  'Guyana',
  'Haiti',
  'Honduras',
  'Hungary',
  'Iceland',
  'India',
  'Indonesia',
  'Iran',
  'Iraq',
  'Ireland',
  'Israel',
  'Italy',
  'Ivory Coast',
  'Jamaica',
  'Japan',
  'Jordan',
  'Kazakhstan',
  'Kenya',
  'Kiribati',
  'Korea North',
  'Korea South',
  'Kosovo',
  'Kuwait',
  'Kyrgyzstan',
  'Laos',
  'Latvia',
  'Lebanon',
  'Lesotho',
  'Liberia',
  'Libya',
  'Liechtenstein',
  'Lithuania',
  'Luxembourg',
  'Macedonia',
  'Madagascar',
  'Malawi',
  'Malaysia',
  'Maldives',
  'Mali',
  'Malta',
  'Marshall Islands',
  'Mauritania',
  'Mauritius',
  'Mexico',
  'Micronesia',
  'Moldova',
  'Monaco',
  'Mongolia',
  'Montenegro',
  'Morocco',
  'Mozambique',
  'Myanmar (Burma)',
  'Namibia',
  'Nauru',
  'Nepal',
  'Netherlands',
  'New Zealand',
  'Nicaragua',
  'Niger',
  'Nigeria',
  'Norway',
  'Oman',
  'Pakistan',
  'Palau',
  'Panama',
  'Papua New Guinea',
  'Paraguay',
  'Peru',
  'Philippines',
  'Poland',
  'Portugal',
  'Qatar',
  'Romania',
  'Russian Federation',
  'Rwanda',
  'St Kitts & Nevis',
  'St Lucia',
  'Saint Vincent & the Grenadines',
  'Samoa',
  'San Marino',
  'Sao Tome & Principe',
  'Saudi Arabia',
  'Senegal',
  'Serbia',
  'Seychelles',
  'Sierra Leone',
  'Singapore',
  'Slovakia',
  'Slovenia',
  'Solomon Islands',
  'Somalia',
  'South Africa',
  'South Sudan',
  'Spain',
  'Sri Lanka',
  'Sudan',
  'Suriname',
  'Swaziland',
  'Sweden',
  'Switzerland',
  'Syria',
  'Taiwan',
  'Tajikistan',
  'Tanzania',
  'Thailand',
  'Togo',
  'Tonga',
  'Trinidad & Tobago',
  'Tunisia',
  'Turkey',
  'Turkmenistan',
  'Tuvalu',
  'Uganda',
  'Ukraine',
  'United Arab Emirates',
  'United Kingdom',
  'United States',
  'Uruguay',
  'Uzbekistan',
  'Vanuatu',
  'Vatican City',
  'Venezuela',
  'Vietnam',
  'Yemen',
  'Zambia',
  'Zimbabwe'
];

const states = [
  'Alabama (AL)',
  'Alaska (AK)',
  'Arizona (AZ)',
  'Arkansas (AR)',
  'California (CA)',
  'Colorado (CO)',
  'Connecticut (CT)',
  'Delaware (DE)',
  'District of Columbia (DC)',
  'Florida (FL)',
  'Georgia (GA)',
  'Hawaii (HI)',
  'Idaho (ID)',
  'Illinois (IL)',
  'Indiana (IN)',
  'Iowa (IA)',
  'Kansas (KS)',
  'Kentucky (KY)',
  'Louisiana (LA)',
  'Maine (ME)',
  'Maryland (MD)',
  'Massachusetts (MA)',
  'Michigan (MI)',
  'Minnesota (MN)',
  'Mississippi (MS)',
  'Missouri (MO)',
  'Montana (MT)',
  'Nebraska (NE)',
  'Nevada (NV)',
  'New Hampshire (NH)',
  'New Jersey (NJ)',
  'New Mexico (NM)',
  'New York (NY)',
  'North Carolina (NC)',
  'North Dakota (ND)',
  'Ohio (OH)',
  'Oklahoma (OK)',
  'Oregon (OR)',
  'Pennsylvania (PA)',
  'Rhode Island (RI)',
  'South Carolina (SC)',
  'South Dakota (SD)',
  'Tennessee (TN)',
  'Texas (TX)',
  'Utah (UT)',
  'Vermont (VT)',
  'Virginia (VA)',
  'Washington (WA)',
  'West Virginia (WV)',
  'Wisconsin (WI)',
  'Wyoming (WY)',
  'American Samoa (AS)',
  'Guam	(GU)',
  'Northern Mariana Islands (MP)',
  'Puerto Rico (PR)',
  'Virgin Islands (VI)',
  'Armed Forces Africa (AE)',
  'Armed Forces Americas (AA)',
  'Armed Forces Canada (AE)',
  'Armed Forces Europe (AE)',
  'Armed Forces Middle East (AE)',
  'Armed Forces Pacific (AP)'
];

const languages = [
  'Arabic',
  'Bengali',
  'Cantonese',
  'English',
  'Farsi',
  'French',
  'German',
  'Hindi',
  'Italian',
  'Mandarin',
  'Portuguese',
  'Punjabi',
  'Russian',
  'Spanish',
  'Vietnamese'
];

const educations = [
  'Grade School',
  'High School',
  'Vocational Training',
  'Some College',
  '2-year College',
  '4-year College',
  'Graduate School'
];

const degrees = [
  'Diploma or GED',
  'Associate of Applied Business (AAB)',
  'Associate of Applied Science (AAS)',
  'Associate of Applied Technology (AAT)',
  'Associate of Arts (AA)',
  'Associate of Science (AS)',
  'Associate of Technology (AT)',
  'Bachelor of Accountancy (BAcy)',
  'Bachelor of Arts (BA, AB)',
  'Bachelor of Applied Arts (BAA)',
  'Bachelor of Applied Arts and Science (BAAS)',
  'Bachelor of Applied Science (BASc)',
  'Bachelor of Business (BBus)',
  'Bachelor of Science (BS)',
  'Bachelor of Technology (BTech)',
  'Master of Accountancy (MAcy)',
  'Master of Applied Science (MASc)',
  'Master of Architecture (MArch)',
  'Master of Arts (MA)',
  'Master of Business (MBS)',
  'Master of Business Administration (MBA)',
  'Master of Divinity (MDiv)',
  'Master of Education (MEd)',
  'Master of Health Science (MHS)',
  'Master of Information System Management (MIM)',
  'Master of Library and Information Science (MLIS)',
  'Master of Science (MS)',
  'Master of Social Work (MSW)',
  'Doctor of Arts (DA)',
  'Doctor of Applied Science )DAS)',
  'Doctor of Education (EdD)',
  'Doctor of Fine Arts (DFA)',
  'Doctor of Juridical Science (JSD)',
  'Doctor of Library Science (DLS)',
  'Doctor of Philosophy (PhD)',
  'Doctor of Science (DSc)',
  'Chiropractic (DC, DCM)',
  'Dentistry (DDS, DMD)',
  'Law (LLB, JD)',
  'Medicine (MD)',
  'Optometry (OD)',
  'Osteopathic Medicine (DO)',
  'Pharmacy (PharmD)',
  'Podiatry (DPM, DP, PodD)',
  'Theology (ordination)',
  'Veterinary Medicine (DVM, VMD)'
];

const races = [
  'American Indian or Native Alaskan',
  'Asian',
  'Black or African American',
  'Middle Eastern or North African',
  'Native Hawaiian or Pacific Inlander',
  'White'
];

const genders = [
  'Woman',
  'Man',
  'Trans woman',
  'Cis woman',
  'Trans man',
  'Cis man',
  'Genderqueer',
  'Non-binary',
  'Bigender',
  'Agender',
  'Two-spirit',
  'AFAB',
  'AMAB',
  'Gender fluid',
  'Gender non-conforming',
  'Trans femme',
  'Trans masc'
];

const sexualities = [
  'Asexual',
  'Bisexual',
  'Gay',
  'Lesbian',
  'Pansexual',
  'Queer',
  'Questioning',
  'Straight'
];

const foodAllergies = [
  'eggs',
  'fish',
  'milk',
  'peanuts',
  'shellfish',
  'soy',
  'tree nuts',
  'wheat'
];

const foodDiets = [
  'halal',
  'kosher',
  'non-alcoholic',
  'non-caffeinated',
  'pescetarian',
  'vegan',
  'vegetarian, lacto-ovo',
  'vegetarian, lacto',
  'vegetarian, ovo'
];
